server:
  port: 8087
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/flowable-demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null
  configuration-properties:
    blobType: BLOB
    boolValue: TRUE
    prefix:

flowable:
  async-executor-activate: false
  database-schema-update: false
  common:
    app:
      idm-url: http://localhost:${server.port}/flowable-idm
  modeler:
    app:
      deployment-api-url: http://localhost:${server.port}/

api:
  boot:
    swagger:
      title: Swagger2 文档
      description: "restful Api"
      version: "1.0"
      license: ""
      license-url: ""
      contact:
        name: dcy
        website: ""
        email: ""
      authorization:
        name: oauth2.0 认证头信息